environment: development
namespace: calculator
hpa:
  minReplicas: 3
  maxReplicas: 12
  cpu: 60
container:
  name: multiply-api
  port: 5000
  image: 389833669077.dkr.ecr.us-west-2.amazonaws.com/eks_practice_multiply
  tag: 8a86c75
  imagePullPolicy: Always
  resources:
    memory: 512Mi
    cpu: 200m
  limits:
    memory: 512Mi
    cpu: 400m
  livenessProbe:
    httpGet:
      path: /multiply/ping
      port: 5000
    initialDelaySeconds: 3
    periodSeconds: 3
  readinessProbe:
    httpGet:
      path: /multiply/ping
      port: 5000
    initialDelaySeconds: 5
    periodSeconds: 5
  pdb:
    minAvailable: 2
replicas: 3
service:
  port: 80
