apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.container.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.container.name }}
spec:
  minAvailable: {{ .Values.container.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}

