apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}-service
  labels:
    app: {{ .Values.container.name }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.container.readinessProbe.httpGet.path }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
    protocol: TCP
    targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.container.name }}
  type: NodePort
