environment: development
namespace: calculator
hpa:
  minReplicas: 3
  maxReplicas: 12
  cpu: 60
container:
  name: divide-api
  port: 5000
  image: ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/eks_practice_divide
  tag: 8a86c75
  imagePullPolicy: Always
  resources:
    memory: 512Mi
    cpu: 200m
  limits:
    memory: 512Mi
    cpu: 400m
  livenessProbe:
    httpGet:
      path: /divide/ping
      port: 5000
    initialDelaySeconds: 3
    periodSeconds: 3
  readinessProbe:
    httpGet:
      path: /divide/ping
      port: 5000
    initialDelaySeconds: 5
    periodSeconds: 5
  pdb:
    minAvailable: 2
replicas: 3
service:
  port: 80
