version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    # - REPOSITORY_URI=<ACCOUNT-ID>.dkr.ecr.<REGION>.amazonaws.com/<BASE-REPO-NAME>
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd ${CODEBUILD_SRC_DIR}/services/plus/
      - REPOSITORY_URI=389833669077.dkr.ecr.us-west-2.amazonaws.com/eks_practice_plus
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo =======================================================
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd ${CODEBUILD_SRC_DIR}/services/minus/
      - REPOSITORY_URI=389833669077.dkr.ecr.us-west-2.amazonaws.com/eks_practice_minus
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo =======================================================
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd ${CODEBUILD_SRC_DIR}/services/divide/
      - REPOSITORY_URI=389833669077.dkr.ecr.us-west-2.amazonaws.com/eks_practice_divide
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo =======================================================
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd ${CODEBUILD_SRC_DIR}/services/multiply/
      - REPOSITORY_URI=389833669077.dkr.ecr.us-west-2.amazonaws.com/eks_practice_multiply
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - echo Pushing the Docker images...
#       - docker push $REPOSITORY_URI:latest
#       - docker push $REPOSITORY_URI:$IMAGE_TAG
#       - echo Writing image definitions file...
#       - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json

# artifacts:
#   base-directory: ${CODEBUILD_SRC_DIR}/services
#   files:
#     - imageDetail.json
