apiVersion: v1
kind: Service
metadata:
  name: minus-api
  namespace: calculator
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 5000
  selector:
    app: minus-api
